/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param moradaID 
 * @param clientID 
 * @param entidadetipo 
 * @param tipoMorada 
 * @param primeiroNome 
 * @param ultimoNome 
 * @param endereco 
 * @param cidade 
 * @param estado 
 * @param cep 
 * @param pais 
 * @param latitude 
 * @param longitude 
 * @param descricao 
 */
data class Address (

    val moradaID: kotlin.Int? = null,
    val clientID: kotlin.String? = null,
    val entidadetipo: kotlin.String? = null,
    val tipoMorada: kotlin.String? = null,
    val primeiroNome: kotlin.String? = null,
    val ultimoNome: kotlin.String? = null,
    val endereco: kotlin.String? = null,
    val cidade: kotlin.String? = null,
    val estado: kotlin.String? = null,
    val cep: kotlin.String? = null,
    val pais: kotlin.String? = null,
    val latitude: kotlin.String? = null,
    val longitude: kotlin.String? = null,
    val descricao: kotlin.String? = null
) {
}