/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param id 
 * @param idExterno 
 * @param nomeCompleto 
 * @param nome 
 * @param descricao 
 * @param extensao 
 * @param tipo 
 * @param utilizador 
 * @param anexo 
 */
data class Attach (

    var id: kotlin.Int? = null,
    var idExterno: kotlin.String? = null,
    var nomeCompleto: kotlin.String? = null,
    var nome: kotlin.String? = null,
    var descricao: kotlin.String? = null,
    var extensao: kotlin.String? = null,
    var tipo: Int? = null,
    var utilizador: kotlin.Int? = null,
    var anexo: kotlin.String? = null
) {
}