/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

import com.microplus.wsGestplus.models.Country
import com.microplus.wsGestplus.models.Equipment

/**
 * 
 * @param objEquipments 
 * @param idFilial 
 * @param descricao 
 * @param idCliente 
 * @param isSede 
 * @param nome 
 * @param morada 
 * @param codigoPostal 
 * @param localidadePostal 
 * @param moradaeLocalidade 
 * @param nomeMorada 
 * @param pais 
 * @param distrito 
 * @param cidade 
 * @param email 
 * @param telefone 
 * @param telemovel 
 */
data class BranchOffice (

    val objEquipments: kotlin.Array<Equipment>? = null,
    val idFilial: kotlin.Int? = null,
    val descricao: kotlin.String? = null,
    val idCliente: kotlin.String? = null,
    val isSede: kotlin.Boolean? = null,
    val nome: kotlin.String? = null,
    val morada: kotlin.String? = null,
    val codigoPostal: kotlin.String? = null,
    val localidadePostal: kotlin.String? = null,
    val moradaeLocalidade: kotlin.Any? = null,
    val nomeMorada: kotlin.Any? = null,
    val pais: Country? = null,
    val distrito: kotlin.Int? = null,
    val cidade: kotlin.Int? = null,
    val email: kotlin.String? = null,
    val telefone: kotlin.String? = null,
    val telemovel: kotlin.String? = null
) {
}