/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param abreviatura 
 * @param program 
 * @param precoPredefinidoCat 
 * @param idCategoriaMain 
 * @param descricao 
 */
data class CategoryMain (

    val abreviatura: kotlin.String? = null,
    val program: kotlin.String? = null,
    val precoPredefinidoCat: kotlin.Int? = null,
    val idCategoriaMain: kotlin.Int? = null,
    val descricao: kotlin.String? = null
) {
}