/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param checklistID 
 * @param descricao 
 * @param viaturaID 
 */
data class CheckList (

    val checklistID: kotlin.Int? = null,
    val descricao: kotlin.String? = null,
    val viaturaID: kotlin.Int? = null
) {
}