/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param nomecomercial 
 * @param imgCertificacaoEmpresa 
 * @param datasNasReferencias 
 * @param versionCert 
 * @param modalidade 
 * @param pathCertificate 
 * @param passCertificate 
 * @param dontShowColoredLinesInDocuments 
 * @param heightA4IMG 
 * @param distanceCompanyBank 
 * @param distanceCompanyEmp 
 * @param spaceTopPayment 
 * @param widthA4IMG 
 * @param chaveIfthen 
 * @param retencoesClienteEstado 
 * @param mbSubentidade 
 * @param swift 
 * @param iban 
 * @param nib 
 * @param esconderComponentes 
 * @param codigoComerciante 
 * @param entidade 
 * @param motIsencaoPos 
 * @param saftpCompanyAddressCountry 
 * @param cltPos 
 * @param descontosHierarquia 
 * @param banco 
 * @param bancoCustom 
 * @param rodapeMail 
 * @param saftpHeaderComment 
 * @param saftpProductVersion 
 * @param saftpProductID 
 * @param saftpCurrencyCode 
 * @param saftpCompanyName 
 * @param saftpCompanyAddressStreetName 
 * @param saftpAdressDetail 
 * @param saftpCompanyAddressCity 
 * @param saftpCompanyAddressPostalCode 
 * @param saftpCompanyAddressRegion 
 * @param saftpTelephone 
 * @param saftpWebsite 
 * @param saftpTaxRegistrationNumber 
 * @param saftpFax 
 * @param saftpEmail 
 * @param envioDocTransp 
 * @param detalhesSuperior 
 * @param maximoConexoes 
 * @param serial 
 * @param imagem 
 * @param pais 
 * @param ftpAdress 
 * @param ftpUser 
 * @param ftpPass 
 * @param dataUltimaActualizacaoConfig 
 * @param ivaIncluido 
 * @param imagemFtpTabela 
 * @param produtosPorArmazem 
 * @param usaProdutosCoresTamanhos 
 * @param stockServicos 
 * @param temLotes 
 * @param eprinterEmail 
 * @param mbSerie 
 * @param posEspacamento 
 * @param notaPOS 
 * @param saftpAuditFileVersion 
 * @param saftpCompanyID 
 * @param saftpTaxAccountingBasis 
 * @param saftpCompanyAddressBuildingNumber 
 * @param capitalSocial 
 * @param conservatorio 
 */
data class ConfigCompany (

    val nomecomercial: kotlin.String? = null,
    val imgCertificacaoEmpresa: kotlin.String? = null,
    val datasNasReferencias: kotlin.Int? = null,
    val versionCert: kotlin.Int? = null,
    val modalidade: Int? = null,
    val pathCertificate: kotlin.String? = null,
    val passCertificate: kotlin.String? = null,
    val dontShowColoredLinesInDocuments: kotlin.Boolean? = null,
    val heightA4IMG: kotlin.Int? = null,
    val distanceCompanyBank: kotlin.Int? = null,
    val distanceCompanyEmp: kotlin.Int? = null,
    val spaceTopPayment: kotlin.Int? = null,
    val widthA4IMG: kotlin.Int? = null,
    val chaveIfthen: kotlin.String? = null,
    val retencoesClienteEstado: kotlin.String? = null,
    val mbSubentidade: kotlin.Int? = null,
    val swift: kotlin.String? = null,
    val iban: kotlin.String? = null,
    val nib: kotlin.String? = null,
    val esconderComponentes: kotlin.Boolean? = null,
    val codigoComerciante: kotlin.String? = null,
    val entidade: kotlin.Int? = null,
    val motIsencaoPos: kotlin.Int? = null,
    val saftpCompanyAddressCountry: kotlin.String? = null,
    val cltPos: kotlin.String? = null,
    val descontosHierarquia: kotlin.Boolean? = null,
    val banco: kotlin.String? = null,
    val bancoCustom: kotlin.String? = null,
    val rodapeMail: kotlin.String? = null,
    val saftpHeaderComment: kotlin.String? = null,
    val saftpProductVersion: kotlin.String? = null,
    val saftpProductID: kotlin.String? = null,
    val saftpCurrencyCode: kotlin.String? = null,
    val saftpCompanyName: kotlin.String? = null,
    val saftpCompanyAddressStreetName: kotlin.String? = null,
    val saftpAdressDetail: kotlin.String? = null,
    val saftpCompanyAddressCity: kotlin.String? = null,
    val saftpCompanyAddressPostalCode: kotlin.String? = null,
    val saftpCompanyAddressRegion: kotlin.String? = null,
    val saftpTelephone: kotlin.String? = null,
    val saftpWebsite: kotlin.String? = null,
    val saftpTaxRegistrationNumber: kotlin.String? = null,
    val saftpFax: kotlin.String? = null,
    val saftpEmail: kotlin.String? = null,
    val envioDocTransp: kotlin.Boolean? = null,
    val detalhesSuperior: kotlin.Boolean? = null,
    val maximoConexoes: kotlin.Int? = null,
    val serial: kotlin.String? = null,
    val imagem: kotlin.String? = null,
    val pais: kotlin.String? = null,
    val ftpAdress: kotlin.String? = null,
    val ftpUser: kotlin.String? = null,
    val ftpPass: kotlin.String? = null,
    val dataUltimaActualizacaoConfig: java.time.LocalDateTime? = null,
    val ivaIncluido: kotlin.Boolean? = null,
    val imagemFtpTabela: kotlin.Boolean? = null,
    val produtosPorArmazem: kotlin.Boolean? = null,
    val usaProdutosCoresTamanhos: kotlin.Boolean? = null,
    val stockServicos: kotlin.Boolean? = null,
    val temLotes: kotlin.Boolean? = null,
    val eprinterEmail: kotlin.String? = null,
    val mbSerie: kotlin.Int? = null,
    val posEspacamento: kotlin.Int? = null,
    val notaPOS: kotlin.String? = null,
    val saftpAuditFileVersion: kotlin.String? = null,
    val saftpCompanyID: kotlin.String? = null,
    val saftpTaxAccountingBasis: kotlin.String? = null,
    val saftpCompanyAddressBuildingNumber: kotlin.String? = null,
    val capitalSocial: kotlin.String? = null,
    val conservatorio: kotlin.String? = null
) {
}