/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param phoneId 
 * @param contactId 
 * @param phoneNumber 
 * @param type 
 */
data class ContactPhoneNumber (

    val phoneId: kotlin.Int? = null,
    val contactId: kotlin.Int? = null,
    val phoneNumber: kotlin.String? = null,
    val type: kotlin.Int? = null
) {
}