/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param contactId 
 * @param resourceName 
 * @param displayName 
 * @param givenName 
 * @param familyName 
 * @param creationTime 
 * @param clientId 
 * @param entidadeTipo 
 */
data class Contact (

    val contactId: kotlin.Int? = null,
    val resourceName: kotlin.String? = null,
    val displayName: kotlin.String? = null,
    val givenName: kotlin.String? = null,
    val familyName: kotlin.String? = null,
    val creationTime: java.time.LocalDateTime? = null,
    val clientId: kotlin.String? = null,
    val entidadeTipo: kotlin.String? = null
) {
}