/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param id 
 * @param nome 
 * @param iso 
 * @param iso3 
 * @param paisDefault 
 */
data class Country (

    val id: kotlin.Int? = null,
    val nome: kotlin.String? = null,
    val iso: kotlin.String? = null,
    val iso3: kotlin.String? = null,
    val paisDefault: kotlin.Boolean? = null
) {
}