/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param idZona 
 * @param idCidade 
 * @param cidade 
 */
data class County (

    val idZona: kotlin.Int? = null,
    val idCidade: kotlin.Int? = null,
    val cidade: kotlin.String? = null
) {
}