/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param localizacao 
 * @param siglaSaft 
 * @param idPais 
 * @param idZona 
 * @param nomeZona 
 */
data class District (

    val localizacao: kotlin.Int? = null,
    val siglaSaft: kotlin.String? = null,
    val idPais: kotlin.Int? = null,
    val idZona: kotlin.Int? = null,
    val nomeZona: kotlin.String? = null
) {
}