/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param idDoc 
 * @param docID 
 * @param movimento 
 * @param anulado 
 * @param iDLoja 
 * @param idCliente 
 * @param numeroDocumento 
 * @param numeroDocumentoFinal 
 * @param moradaEntrega 
 * @param localidadeEntrega 
 * @param numeroDocumentoOffline 
 * @param nomeCliente 
 * @param tDocRascName 
 * @param empresaCliente 
 * @param nomeOuEmpresa 
 * @param totalDocumento 
 * @param dataDocumento 
 * @param utilizadorCriacaoDocumento 
 * @param tDoc 
 * @param metodoPagamentoDocumento 
 * @param numeroPagamento 
 * @param talaoDeposito 
 * @param banco 
 * @param estado 
 * @param faturado 
 * @param docforn 
 * @param atCodeID 
 * @param atCodeError 
 * @param sigla 
 * @param idTipo 
 * @param pago 
 * @param valorRemanescente 
 * @param descricao 
 * @param tipoentidade 
 * @param idEstadoTecnico 
 * @param idTecnico 
 * @param dataFim 
 * @param nif 
 * @param ticket 
 * @param idTicketPriority 
 * @param dataPedido 
 * @param dataConclusao 
 */
data class DocumentSearch (

    val id_Doc: kotlin.Int? = null,
    val docID: kotlin.String? = null,
    val movimento: kotlin.String? = null,
    val anulado: kotlin.Boolean? = null,
    val iD_Loja: kotlin.String? = null,
    val id_Cliente: kotlin.String? = null,
    val numero_documento: kotlin.Int? = null,
    val numero_documento_final: kotlin.String? = null,
    val morada_Entrega: kotlin.String? = null,
    val localidade_entrega: kotlin.String? = null,
    val numero_documento_offline: kotlin.String? = null,
    val nome_cliente: kotlin.String? = null,
    val tDocRascName: kotlin.String? = null,
    val empresa_cliente: kotlin.String? = null,
    val nome_ou_empresa: kotlin.Any? = null,
    val total_documento: kotlin.Double? = null,
    val data_documento: java.time.LocalDateTime? = null,
    val utilizador_criacao_documento: kotlin.String? = null,
    val tDoc: kotlin.String? = null,
    val metodo_pagamento_documento: kotlin.String? = null,
    val numero_pagamento: kotlin.String? = null,
    val talao_deposito: kotlin.String? = null,
    val banco: kotlin.String? = null,
    val estado: kotlin.String? = null,
    val faturado: kotlin.Boolean? = null,
    val docforn: kotlin.String? = null,
    val atCodeID: kotlin.String? = null,
    val atCodeError: kotlin.String? = null,
    val sigla: kotlin.String? = null,
    val idTipo: kotlin.Int? = null,
    val pago: kotlin.Boolean? = null,
    val valorRemanescente: kotlin.Double? = null,
    val descricao: kotlin.String? = null,
    val tipoentidade: kotlin.Int? = null,
    val idEstadoTecnico: kotlin.Int? = null,
    val idTecnico: kotlin.Int? = null,
    val data_fim: java.time.LocalDateTime? = null,
    val nif: kotlin.String? = null,
    val ticket: TicketSearch? = null,
    val idTicketPriority: kotlin.Int? = null,
    val data_pedido: java.time.LocalDateTime? = null,
    val data_conclusao: java.time.LocalDateTime? = null
) {
}