/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 *
 * @param tmpIdM
 * @param iditem
 * @param itemDocIDHistorico
 * @param itemDocIDOrigemHistorico
 * @param itemdocID
 * @param docID
 * @param itemdocIDOrigem
 * @param nDocumento
 * @param idtipo
 * @param idequip
 * @param contagem
 * @param idcliente
 * @param idproduto
 * @param anulado
 * @param codprod
 * @param codbarras
 * @param marca
 * @param nome
 * @param nomeeCodigo
 * @param nomeequant
 * @param nomeequanteDesc
 * @param desccomp
 * @param compra
 * @param precoConverted
 * @param precoMaximo
 * @param precoDoc
 * @param iva
 * @param retencao
 * @param retencaotot
 * @param tipoiva
 * @param devolvido
 * @param serialList
 * @param reqSerial
 * @param comissaoMicroplus
 * @param numeroDoc
 * @param tipoProd
 * @param &#x60;data&#x60;
 * @param dataVencimento
 * @param dataMarcacao
 * @param eccCredito
 * @param eccDebito
 * @param vReferencia
 * @param vEncomenda
 * @param docRecibo
 * @param tipoDocRecibo
 * @param entregue
 * @param refNTC
 * @param refNTCTipoDoc
 * @param idCompra
 * @param iva2Hand
 * @param devolvidoQuant
 * @param numeroEnc
 * @param qtdConfirmadaPag
 * @param processado
 * @param unidade
 * @param reservado
 * @param numeroEncFornecedor
 * @param produtoFoiTrocado
 * @param stock
 * @param stockTipo
 * @param movimento
 * @param desconto
 * @param desconto2
 * @param desconto3
 * @param descontofinanceiro
 * @param descontoCliente
 * @param entregarPos
 * @param estado
 * @param idVenda
 * @param idOP
 * @param sessionID
 * @param idSerie
 * @param idLoja
 * @param codARM
 * @param produtoPai
 * @param visivelDoc
 * @param tara
 * @param taraPerdida
 * @param objLote
 * @param dataEntrega
 * @param despCozinha
 * @param facturadoQuant
 * @param setPVenda
 * @param objGestor
 * @param objVendedor
 * @param referenteDocumentoNome
 * @param referenteDocumentoNumero
 * @param referenteDocumentoTipo
 * @param referenteDocumentoPrograma
 * @param referenteDocumentoLoja
 * @param referenteDocumentoDescricao
 * @param referenteDocumentoSerie
 * @param sn
 * @param licensenumber
 * @param salesnumber
 * @param mediaCondition
 * @param sleeveCondition
 * @param newCondition
 * @param objMotivoIsencao
 * @param idMotivoIsencao
 * @param abreviatura
 * @param codForn
 * @param typeProg
 * @param ultimoPrecoCompra
 * @param precoMedioCompra
 * @param precoMedioVenda
 * @param precoTabela
 * @param objTotaisLinha
 * @param objTotaisLinhaConversao
 * @param quant
 * @param quantAFaturar
 * @param ivANome
 * @param reqSerialProd
 * @param ultimoPrecoVenda
 * @param snCProdutoBase
 * @param snCProdutoIVA
 * @param referenteDocumentoNomeDestino
 * @param referenteDocumentoNumeroDestino
 * @param referenteDocumentoTipoDestino
 * @param referenteDocumentoProgramaDestino
 * @param referenteDocumentoLojaDestino
 * @param referenteDocumentoDescricaoDestino
 * @param refNTCIDLoja
 * @param ano
 * @param mes
 * @param idFornecedor
 * @param objServico
 * @param irSValor
 * @param irSTaxa
 * @param subTotal
 * @param preco
 * @param valorOriginal
 * @param valorOriginalDOC
 * @param valorPendente
 * @param valorIVATotal
 * @param total
 * @param subTotalConverted
 * @param valorIVATotalConverted
 * @param totalConverted
 * @param comissaoPercentagemA
 * @param comissaoPercentagemB
 * @param comissaoValorA
 * @param comissaoValorB
 * @param version
 * @param getDescCompFinal
 * @param idVoucher
 * @param idEntidadeVoucher
 * @param codigoVoucher
 * @param percentagemComissao
 * @param valorComissao
 * @param sentPrinterAux
 * @param printerAuxId
 * @param idTicketIntervencao
 * @param ticketDataContador
 * @param ticketContadorEstado
 * @param idEntidadeExtra
 * @param idEntidadeExtraTipo
 */
data class DocumentLine (

    val tmpIdM: kotlin.Any? = null,
    val iditem: kotlin.Int? = null,
    val itemDocIDHistorico: kotlin.String? = null,
    val itemDocIDOrigemHistorico: kotlin.String? = null,
    val itemdocID: kotlin.String? = null,
    val docID: kotlin.String? = null,
    val itemdocIDOrigem: kotlin.String? = null,
    val nDocumento: kotlin.String? = null,
    val idtipo: kotlin.Int? = null,
    val idequip: kotlin.Int? = null,
    val contagem: kotlin.Double? = null,
    val idcliente: kotlin.String? = null,
    val idproduto: kotlin.Int? = null,
    val anulado: kotlin.Boolean? = null,
    val codprod: kotlin.String? = null,
    val codbarras: kotlin.String? = null,
    val marca: kotlin.Int? = null,
    val nome: kotlin.String? = null,
    val nomeeCodigo: kotlin.String? = null,
    val nomeequant: kotlin.String? = null,
    val nomeequanteDesc: kotlin.String? = null,
    var desccomp: kotlin.String? = null,
    val compra: kotlin.Double? = null,
    val precoConverted: kotlin.Double? = null,
    val precoMaximo: kotlin.Double? = null,
    val precoDoc: kotlin.Double? = null,
    val iva: kotlin.Double? = null,
    val retencao: kotlin.Double? = null,
    val retencaotot: kotlin.Double? = null,
    val tipoiva: Int? = null,
    val devolvido: kotlin.Boolean? = null,
    val serialList: kotlin.Array<SerialNumber>? = null,
    val reqSerial: kotlin.Boolean? = null,
    val comissaoMicroplus: kotlin.Boolean? = null,
    val numeroDoc: kotlin.Int? = null,
    val tipoProd: Int? = null,
    val `data`: kotlin.String? = null,
    val dataVencimento: kotlin.String? = null,
    val dataMarcacao: kotlin.String? = null,
    val eccCredito: kotlin.Double? = null,
    val eccDebito: kotlin.Double? = null,
    val vReferencia: kotlin.String? = null,
    val vEncomenda: kotlin.String? = null,
    val docRecibo: kotlin.String? = null,
    val tipoDocRecibo: kotlin.Int? = null,
    val entregue: kotlin.Int? = null,
    val refNTC: kotlin.String? = null,
    val refNTCTipoDoc: kotlin.Int? = null,
    val idCompra: kotlin.Int? = null,
    val iva2Hand: kotlin.Int? = null,
    val devolvidoQuant: kotlin.Double? = null,
    val numeroEnc: kotlin.Int? = null,
    val qtdConfirmadaPag: kotlin.Int? = null,
    val processado: kotlin.Boolean? = null,
    val unidade: kotlin.String? = null,
    val reservado: kotlin.Int? = null,
    val numeroEncFornecedor: kotlin.Int? = null,
    val produtoFoiTrocado: kotlin.Boolean? = null,
    val stock: kotlin.String? = null,
    val stockTipo: kotlin.Int? = null,
    val movimento: kotlin.String? = null,
    val desconto: kotlin.Double? = null,
    val desconto2: kotlin.Double? = null,
    val desconto3: kotlin.Double? = null,
    val descontofinanceiro: kotlin.Double? = null,
    val descontoCliente: kotlin.Double? = null,
    val entregarPos: kotlin.Boolean? = null,
    val estado: kotlin.String? = null,
    val idVenda: kotlin.Int? = null,
    val idOP: kotlin.Int? = null,
    val sessionID: kotlin.String? = null,
    val idSerie: kotlin.String? = null,
    val idLoja: kotlin.String? = null,
    val codARM: kotlin.String? = null,
    val produtoPai: kotlin.Int? = null,
    val visivelDoc: kotlin.Boolean? = null,
    val tara: kotlin.Boolean? = null,
    val taraPerdida: kotlin.Boolean? = null,
    val objLote: Lot? = null,
    val dataEntrega: kotlin.String? = null,
    val despCozinha: kotlin.Boolean? = null,
    val facturadoQuant: kotlin.Double? = null,
    val setPVenda: kotlin.Double? = null,
    val objGestor: EntityAssociated? = null,
    val objVendedor: EntityAssociated? = null,
    val referenteDocumentoNome: kotlin.String? = null,
    val referenteDocumentoNumero: kotlin.Int? = null,
    val referenteDocumentoTipo: TypeDocument? = null,
    val referenteDocumentoPrograma: kotlin.Int? = null,
    val referenteDocumentoLoja: kotlin.String? = null,
    val referenteDocumentoDescricao: kotlin.String? = null,
    val referenteDocumentoSerie: kotlin.String? = null,
    val sn: kotlin.String? = null,
    val licensenumber: kotlin.String? = null,
    val salesnumber: kotlin.String? = null,
    val mediaCondition: kotlin.Int? = null,
    val sleeveCondition: kotlin.Int? = null,
    val newCondition: kotlin.Boolean? = null,
    val objMotivoIsencao: ReasonsExemption? = null,
    val idMotivoIsencao: kotlin.Int? = null,
    val abreviatura: kotlin.String? = null,
    val codForn: kotlin.String? = null,
    val typeProg: kotlin.String? = null,
    val ultimoPrecoCompra: kotlin.Double? = null,
    val precoMedioCompra: kotlin.Double? = null,
    val precoMedioVenda: kotlin.Double? = null,
    val precoTabela: kotlin.Double? = null,
    val objTotaisLinha: TotalDocumentLine? = null,
    val objTotaisLinhaConversao: TotalDocumentLine? = null,
    val quant: kotlin.Double? = null,
    val quantAFaturar: kotlin.Double? = null,
    val ivANome: kotlin.String? = null,
    val reqSerialProd: kotlin.Boolean? = null,
    val ultimoPrecoVenda: kotlin.Int? = null,
    val snCProdutoBase: kotlin.Int? = null,
    val snCProdutoIVA: kotlin.Int? = null,
    val referenteDocumentoNomeDestino: kotlin.String? = null,
    val referenteDocumentoNumeroDestino: kotlin.Int? = null,
    val referenteDocumentoTipoDestino: kotlin.Int? = null,
    val referenteDocumentoProgramaDestino: kotlin.Int? = null,
    val referenteDocumentoLojaDestino: kotlin.String? = null,
    val referenteDocumentoDescricaoDestino: kotlin.String? = null,
    val refNTCIDLoja: kotlin.String? = null,
    val ano: kotlin.Int? = null,
    val mes: kotlin.Int? = null,
    val idFornecedor: kotlin.Int? = null,
    val objServico: ServiceItemLine? = null,
    val irSValor: kotlin.Double? = null,
    val irSTaxa: kotlin.Double? = null,
    val subTotal: kotlin.Any? = null,
    val preco: kotlin.Double? = null,
    val valorOriginal: kotlin.Double? = null,
    val valorOriginalDOC: kotlin.Double? = null,
    val valorPendente: kotlin.Double? = null,
    val valorIVATotal: kotlin.Any? = null,
    val total: kotlin.Any? = null,
    val subTotalConverted: kotlin.Any? = null,
    val valorIVATotalConverted: kotlin.Any? = null,
    val totalConverted: kotlin.Any? = null,
    val comissaoPercentagemA: kotlin.String? = null,
    val comissaoPercentagemB: kotlin.String? = null,
    val comissaoValorA: kotlin.Double? = null,
    val comissaoValorB: kotlin.Double? = null,
    val version: kotlin.String? = null,
    val getDescCompFinal: kotlin.String? = null,
    val idVoucher: kotlin.Int? = null,
    val idEntidadeVoucher: kotlin.Int? = null,
    val codigoVoucher: kotlin.String? = null,
    val percentagemComissao: kotlin.Double? = null,
    val valorComissao: kotlin.Double? = null,
    val sentPrinterAux: kotlin.Int? = null,
    val printerAuxId: kotlin.Int? = null,
    val idTicketIntervencao: kotlin.Int? = null,
    val ticketDataContador: kotlin.String? = null,
    val ticketContadorEstado: kotlin.Int? = null,
    var idEntidadeExtra: kotlin.String? = null,
    var idEntidadeExtraTipo: kotlin.String? = null
) {
}