/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

import com.microplus.wsGestplus.models.GestError
import com.microplus.wsGestplus.models.TransportDocument
import com.microplus.wsGestplus.models.TypeDocument

/**
 * 
 * @param numeroDoc 
 * @param iDLoja 
 * @param iDSerie 
 * @param docID 
 * @param objTipoDocumento 
 * @param objDocumentoTransporte 
 * @param documentoError 
 * @param receipt 
 */
data class DocumentFinalize (

    val numeroDoc: kotlin.Int? = null,
    val iDLoja: kotlin.String? = null,
    val iDSerie: kotlin.String? = null,
    val docID: kotlin.String? = null,
    val objTipoDocumento: TypeDocument? = null,
    val objDocumentoTransporte: TransportDocument? = null,
    val documentoError: kotlin.Array<GestError>? = null,
    val receipt: kotlin.Array<kotlin.String>? = null
) {
}