/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param entidadeTipo 
 * @param idCliente 
 * @param nomeOuEmpresa 
 * @param codigoCliente 
 * @param nome 
 * @param empresa 
 * @param contribuinte 
 * @param email 
 * @param telefone 
 * @param telemovel 
 * @param pais 
 * @param desconto 
 * @param morada 
 * @param zona 
 * @param cidade 
 * @param codPostal 
 * @param locPostal 
 * @param categoria 
 * @param dataRegisto 
 * @param descEmpresa 
 * @param obs 
 * @param origem 
 * @param descricaoAUsar 
 * @param showFull 
 */
data class EntitySearch (

    val entidadeTipo: kotlin.String? = null,
    val idCliente: kotlin.String? = null,
    val nomeOuEmpresa: kotlin.String? = null,
    val codigoCliente: kotlin.String? = null,
    val nome: kotlin.String? = null,
    val empresa: kotlin.String? = null,
    val contribuinte: kotlin.String? = null,
    val email: kotlin.String? = null,
    val telefone: kotlin.String? = null,
    val telemovel: kotlin.String? = null,
    val pais: kotlin.String? = null,
    val desconto: kotlin.Double? = null,
    val morada: kotlin.String? = null,
    val zona: kotlin.String? = null,
    val cidade: kotlin.String? = null,
    val codPostal: kotlin.String? = null,
    val locPostal: kotlin.String? = null,
    val categoria: kotlin.String? = null,
    val dataRegisto: java.time.LocalDateTime? = null,
    val descEmpresa: kotlin.String? = null,
    val obs: kotlin.String? = null,
    val origem: kotlin.String? = null,
    val descricaoAUsar: kotlin.Any? = null,
    val showFull: kotlin.Any? = null
) {
}