/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

import com.microplus.wsGestplus.models.BranchOfficeList
import com.microplus.wsGestplus.models.Category
import com.microplus.wsGestplus.models.CategoryMain
import com.microplus.wsGestplus.models.Country
import com.microplus.wsGestplus.models.County
import com.microplus.wsGestplus.models.Currency
import com.microplus.wsGestplus.models.District
import com.microplus.wsGestplus.models.EntityAssociated
import com.microplus.wsGestplus.models.GestError
import com.microplus.wsGestplus.models.RegimeIVA
import com.microplus.wsGestplus.models.SubCategory

/**
 *
 * @param nomeOuEmpresa
 * @param idManual
 * @param isFavorito
 * @param idCliente
 * @param nome
 * @param facebookID
 * @param empresa
 * @param morada
 * @param codigoPostal
 * @param localidadePostal
 * @param desconto
 * @param contribuinte
 * @param pais
 * @param email
 * @param telefone
 * @param telemovel
 * @param filiais
 * @param entreganome
 * @param entregamorada
 * @param entregalocpostal
 * @param entregapostal
 * @param entregapais
 * @param objRegimeIva
 * @param err
 * @param emailgerente
 * @param emailFinanceiro
 * @param emailcomercial
 * @param emailnewsletter
 * @param emailtecnico
 * @param entregazona
 * @param objRevendedor
 * @param objGestor
 * @param objVendedor
 * @param objCurrency
 * @param ivadecaixa
 * @param newsletter
 * @param precopredefinido
 * @param temcredito
 * @param limitecredito
 * @param aprovarenviocobranca
 * @param username
 * @param userpassword
 * @param pagamento
 * @param tipoarmazem
 * @param categoriamain
 * @param categoria
 * @param subcategoria
 * @param vencimento
 * @param retemirs
 * @param retemtipo
 * @param descempresa
 * @param cargo
 * @param localidade
 * @param fax
 * @param obs
 * @param cartaoCliente
 * @param zona
 * @param site
 * @param banco
 * @param agencia
 * @param nib
 * @param swift
 * @param iban
 * @param nfr
 * @param nfr2
 * @param numeroTecForm
 * @param distribuidor
 * @param formacao
 * @param contrato
 * @param dataNfr
 * @param dataForm
 * @param dataCont
 * @param dataNasc
 * @param biData
 * @param sexo
 * @param estadoCivil
 * @param profissao
 * @param bi
 * @param biArquivo
 * @param telefoneP
 * @param telemovelP
 * @param emailP
 * @param bloqueado
 * @param cidade
 * @param entregaCidade
 * @param nomePai
 * @param mae
 * @param utilizadorAssociado
 * @param codigoCliente
 * @param codigoCliente2
 * @param descricaoEmpresa
 * @param nomecomercial
 * @param tipoCliente
 * @param modoPagamento
 * @param defaultDocSerie
 * @param sujPassVal
 * @param idPromotorPai
 * @param snc
 * @param contaSNC
 * @param pai
 * @param entidadeTipo
 * @param temDocumentosContabilisticos
 * @param idMotIsento
 */
data class Entity (

    val nomeOuEmpresa: kotlin.String? = null,
    val idManual: kotlin.String? = null,
    val isFavorito: kotlin.Int? = null,
    val idCliente: kotlin.String? = null,
    val nome: kotlin.String? = null,
    val facebookID: kotlin.String? = null,
    val empresa: kotlin.String? = null,
    val morada: kotlin.String? = null,
    val codigoPostal: kotlin.String? = null,
    val localidadePostal: kotlin.String? = null,
    val desconto: kotlin.Double? = null,
    val contribuinte: kotlin.String? = null,
    val pais: Country? = null,
    val email: kotlin.String? = null,
    val telefone: kotlin.String? = null,
    val telemovel: kotlin.String? = null,
    val filiais: BranchOfficeList? = null,
    val entreganome: kotlin.String? = null,
    val entregamorada: kotlin.String? = null,
    val entregalocpostal: kotlin.String? = null,
    val entregapostal: kotlin.String? = null,
    val entregapais: Country? = null,
    val objRegimeIva: RegimeIVA? = null,
    val err: GestError? = null,
    val emailgerente: kotlin.String? = null,
    val emailFinanceiro: kotlin.String? = null,
    val emailcomercial: kotlin.String? = null,
    val emailnewsletter: kotlin.String? = null,
    val emailtecnico: kotlin.String? = null,
    val entregazona: District? = null,
    val objRevendedor: EntityAssociated? = null,
    val objGestor: EntityAssociated? = null,
    val objVendedor: EntityAssociated? = null,
    val objCurrency: Currency? = null,
    val ivadecaixa: kotlin.Boolean? = null,
    val newsletter: kotlin.Boolean? = null,
    val precopredefinido: Int? = null,
    val temcredito: kotlin.Boolean? = null,
    val limitecredito: kotlin.Double? = null,
    val aprovarenviocobranca: kotlin.Boolean? = null,
    val username: kotlin.String? = null,
    val userpassword: kotlin.String? = null,
    val pagamento: kotlin.Int? = null,
    val tipoarmazem: kotlin.String? = null,
    val categoriamain: CategoryMain? = null,
    val categoria: Category? = null,
    val subcategoria: SubCategory? = null,
    val vencimento: kotlin.Int? = null,
    val retemirs: kotlin.Boolean? = null,
    val retemtipo: kotlin.Int? = null,
    val descempresa: kotlin.String? = null,
    val cargo: kotlin.String? = null,
    val localidade: kotlin.String? = null,
    val fax: kotlin.String? = null,
    val obs: kotlin.String? = null,
    val cartaoCliente: kotlin.String? = null,
    val zona: District? = null,
    val site: kotlin.String? = null,
    val banco: kotlin.String? = null,
    val agencia: kotlin.String? = null,
    val nib: kotlin.String? = null,
    val swift: kotlin.String? = null,
    val iban: kotlin.String? = null,
    val nfr: kotlin.String? = null,
    val nfr2: kotlin.String? = null,
    val numeroTecForm: kotlin.Int? = null,
    val distribuidor: kotlin.String? = null,
    val formacao: kotlin.Boolean? = null,
    val contrato: kotlin.Boolean? = null,
    val dataNfr: java.time.LocalDateTime? = null,
    val dataForm: java.time.LocalDateTime? = null,
    val dataCont: java.time.LocalDateTime? = null,
    val dataNasc: java.time.LocalDateTime? = null,
    val biData: java.time.LocalDateTime? = null,
    val sexo: kotlin.String? = null,
    val estadoCivil: kotlin.String? = null,
    val profissao: kotlin.String? = null,
    val bi: kotlin.String? = null,
    val biArquivo: kotlin.String? = null,
    val telefoneP: kotlin.String? = null,
    val telemovelP: kotlin.String? = null,
    val emailP: kotlin.String? = null,
    val bloqueado: kotlin.Boolean? = null,
    val cidade: County? = null,
    val entregaCidade: County? = null,
    val nomePai: kotlin.String? = null,
    val mae: kotlin.String? = null,
    val utilizadorAssociado: kotlin.Int? = null,
    val codigoCliente: kotlin.String? = null,
    val codigoCliente2: kotlin.String? = null,
    val descricaoEmpresa: kotlin.String? = null,
    val nomecomercial: kotlin.String? = null,
    val tipoCliente: kotlin.Int? = null,
    val modoPagamento: kotlin.Int? = null,
    val defaultDocSerie: kotlin.String? = null,
    val sujPassVal: kotlin.Double? = null,
    val idPromotorPai: kotlin.Int? = null,
    val snc: kotlin.Int? = null,
    val contaSNC: kotlin.String? = null,
    val pai: kotlin.Int? = null,
    val entidadeTipo: kotlin.String? = null,
    val temDocumentosContabilisticos: kotlin.Boolean? = null,
    val idMotIsento: kotlin.Int? = null
) {
}