/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param nomeOuEmpresa 
 * @param defaultDocSerie 
 * @param idCliente 
 * @param nome 
 * @param empresa 
 * @param morada 
 * @param codigoPostal 
 * @param localidadePostal 
 * @param desconto 
 * @param contribuinte 
 * @param pais 
 * @param email 
 * @param telefone 
 * @param telemovel 
 * @param filiais 
 * @param retemIRS 
 * @param retemTipo 
 * @param sujPassVal 
 * @param entregaNome 
 * @param entregaMorada 
 * @param entregaLocPostal 
 * @param entregaPostal 
 * @param entregaPais 
 * @param objRegimeIva 
 * @param objRevendedor 
 * @param objGestor 
 * @param objVendedor 
 * @param precoPredefinido 
 * @param entidadeTipo 
 * @param nCartao 
 * @param objCurrency 
 * @param vencimento 
 * @param modoPagamento 
 * @param err 
 * @param idMotIsento 
 */
data class EntityInfo (

    val nomeOuEmpresa: kotlin.String? = null,
    val defaultDocSerie: kotlin.String? = null,
    val idCliente: kotlin.String? = null,
    val nome: kotlin.String? = null,
    val empresa: kotlin.String? = null,
    val morada: kotlin.String? = null,
    val codigoPostal: kotlin.String? = null,
    val localidadePostal: kotlin.String? = null,
    val desconto: kotlin.Double? = null,
    val contribuinte: kotlin.String? = null,
    val pais: Country? = null,
    val email: kotlin.String? = null,
    val telefone: kotlin.String? = null,
    val telemovel: kotlin.String? = null,
    val filiais: BranchOfficeList? = null,
    val retemIRS: kotlin.Boolean? = null,
    val retemTipo: kotlin.Int? = null,
    val sujPassVal: kotlin.Double? = null,
    val entregaNome: kotlin.String? = null,
    val entregaMorada: kotlin.String? = null,
    val entregaLocPostal: kotlin.String? = null,
    val entregaPostal: kotlin.String? = null,
    val entregaPais: Country? = null,
    val objRegimeIva: RegimeIVA? = null,
    val objRevendedor: EntityAssociated? = null,
    val objGestor: EntityAssociated? = null,
    val objVendedor: EntityAssociated? = null,
    val precoPredefinido: kotlin.Int? = null,
    val entidadeTipo: kotlin.String? = null,
    val nCartao: kotlin.String? = null,
    val objCurrency: Currency? = null,
    val vencimento: kotlin.Int? = null,
    val modoPagamento: kotlin.Int? = null,
    val err: GestError? = null,
    val idMotIsento: kotlin.Int? = null
) {
}