/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param idEquip 
 * @param idCliente 
 * @param nome 
 * @param serialN 
 * @param idFilial 
 * @param modeloMarca 
 * @param situacao 
 * @param dataSituacao 
 */
data class Equipment (

    val idEquip: kotlin.Int? = null,
    val idCliente: kotlin.String? = null,
    val nome: kotlin.String? = null,
    val serialN: kotlin.String? = null,
    val idFilial: kotlin.Int? = null,
    val modeloMarca: kotlin.String? = null,
    val situacao: kotlin.String? = null,
    val dataSituacao: java.time.LocalDateTime? = null
) {
}