/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param sorting 
 * @param codigoCliente 
 * @param sortingOrder 
 * @param entidadeTipo 
 * @param apenasComRecibo 
 * @param apenasComServico 
 * @param filtrarArmazensDisponiveis 
 * @param idCliente 
 * @param niFouNome 
 * @param nomeOuEmpresaCliente 
 * @param nomeOuEmpresaClienteInicial 
 * @param contribuinteCliente 
 * @param filtrarFavoritos 
 * @param contribuinteClienteexato 
 * @param emailCliente 
 * @param contactoCliente 
 * @param telefone 
 * @param telefoneexato 
 * @param morada 
 * @param categoriaCliente 
 * @param idCategoriaMain 
 * @param apenasNaoBloquados 
 * @param numeroRegistosPesquisa 
 * @param numeroPaginaPesquisa 
 * @param cartaoCliente 
 * @param nome 
 * @param empresa 
 * @param concelho 
 * @param idPais 
 * @param idZona 
 * @param idCategoria 
 * @param idUtilizador 
 * @param username 
 * @param password 
 * @param validateLogin 
 * @param nomeoucnt 
 */
data class LoadEntitySearch (

    val sorting: Int? = null,
    val codigoCliente: kotlin.String? = null,
    val sortingOrder: Int? = null,
    val entidadeTipo: kotlin.String? = null,
    val apenasComRecibo: kotlin.Boolean? = null,
    val apenasComServico: kotlin.Boolean? = null,
    val filtrarArmazensDisponiveis: kotlin.Boolean? = null,
    val idCliente: kotlin.String? = null,
    val niFouNome: kotlin.String? = null,
    val nomeOuEmpresaCliente: kotlin.String? = null,
    val nomeOuEmpresaClienteInicial: kotlin.String? = null,
    val contribuinteCliente: kotlin.String? = null,
    val filtrarFavoritos: kotlin.String? = null,
    val contribuinteClienteexato: kotlin.String? = null,
    val emailCliente: kotlin.String? = null,
    val contactoCliente: kotlin.String? = null,
    val telefone: kotlin.String? = null,
    val telefoneexato: kotlin.String? = null,
    val morada: kotlin.String? = null,
    val categoriaCliente: CategoryMain? = null,
    val idCategoriaMain: kotlin.Int? = null,
    val apenasNaoBloquados: kotlin.Boolean? = null,
    val numeroRegistosPesquisa: kotlin.Int? = null,
    val numeroPaginaPesquisa: kotlin.Int? = null,
    val cartaoCliente: kotlin.String? = null,
    val nome: kotlin.String? = null,
    val empresa: kotlin.String? = null,
    val concelho: kotlin.String? = null,
    val idPais: kotlin.Int? = null,
    val idZona: kotlin.Int? = null,
    val idCategoria: kotlin.Int? = null,
    val idUtilizador: kotlin.Int? = null,
    val username: kotlin.String? = null,
    val password: kotlin.String? = null,
    val validateLogin: kotlin.Boolean? = null,
    val nomeoucnt: kotlin.String? = null
) {
}