/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param idLoja 
 * @param numeroDoc 
 * @param idSerie 
 * @param tipo 
 * @param docId 
 * @param entidadeTipo 
 * @param webLoad 
 */
data class LoadingData (

    val idLoja: kotlin.String? = null,
    val numeroDoc: kotlin.Int? = null,
    val idSerie: kotlin.String? = null,
    val tipo: kotlin.Int? = null,
    val docId: kotlin.String? = null,
    val entidadeTipo: kotlin.String? = null,
    val webLoad: kotlin.Boolean? = null
) {
}