/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param connection 
 * @param databaseName 
 * @param userDB 
 * @param ipDB 
 * @param passDB 
 * @param idUser 
 * @param session 
 * @param idLoja 
 * @param idSerie 
 * @param origem 
 * @param typeProg 
 */
data class Login (

    val connection: kotlin.String? = null,
    val databaseName: kotlin.String? = null,
    val userDB: kotlin.String? = null,
    val ipDB: kotlin.String? = null,
    val passDB: kotlin.String? = null,
    val idUser: kotlin.Int? = null,
    val session: java.util.UUID? = null,
    val idLoja: kotlin.Int? = null,
    val idSerie: kotlin.String? = null,
    val origem: kotlin.String? = null,
    val typeProg: Int? = null
) {
}