/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

import com.microplus.wsGestplus.models.CheckList
import com.microplus.wsGestplus.models.Viatura

/**
 * 
 * @param objCheckList 
 * @param objViatura 
 */
data class ObjResultgetCheckList (

    val objCheckList: kotlin.Array<CheckList>? = null,
    val objViatura: Viatura? = null
) {
}