/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param phoneNumber 
 * @param clientId 
 * @param entidadeTipo 
 * @param emailAddress 
 */
data class ParamGetContacts (

    val phoneNumber: kotlin.String? = null,
    val clientId: kotlin.String? = null,
    val entidadeTipo: kotlin.String? = null,
    val emailAddress: kotlin.String? = null
) {
}