/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param idproduto 
 * @param usaUltimoPrecoeDesconto 
 * @param unidadevenda 
 * @param unidadecompra 
 * @param codigo 
 * @param codigoBarras 
 * @param codigoFornecedor 
 * @param unidade 
 * @param abreviatura 
 * @param compra 
 * @param fatorconversao 
 * @param obsoleto 
 * @param nome 
 * @param preco 
 * @param preco2 
 * @param preco3 
 * @param prequant 
 * @param desccomp 
 * @param idprodpai 
 * @param idfornecedor 
 * @param obs 
 * @param tipoIva 
 * @param valorIva 
 * @param tipoIvacompra 
 * @param valorIvacompra 
 * @param vencomenda 
 * @param vreferencia 
 * @param quant 
 * @param desconto 
 * @param desconto2 
 * @param upc 
 * @param pcm 
 * @param udc 
 * @param dataentrega 
 * @param tara 
 * @param taraperdida 
 * @param marca 
 * @param reqserial 
 * @param tipoprod 
 * @param objMotivoIsencao 
 * @param objLote 
 * @param usaLote 
 * @param seriallist 
 * @param salesNumber 
 * @param licenseNumber 
 * @param contaSNC 
 * @param defaultArm 
 * @param err 
 */
data class ProductInfo (

    val idproduto: kotlin.Int? = null,
    val usaUltimoPrecoeDesconto: kotlin.Boolean? = null,
    val unidadevenda: kotlin.String? = null,
    val unidadecompra: kotlin.String? = null,
    val codigo: kotlin.String? = null,
    val codigoBarras: kotlin.String? = null,
    val codigoFornecedor: kotlin.String? = null,
    val unidade: kotlin.String? = null,
    val abreviatura: kotlin.String? = null,
    val compra: kotlin.Double? = null,
    val fatorconversao: kotlin.Double? = null,
    val obsoleto: kotlin.Boolean? = null,
    val nome: kotlin.String? = null,
    val preco: kotlin.Double? = null,
    val preco2: kotlin.Double? = null,
    val preco3: kotlin.Double? = null,
    val prequant: kotlin.Double? = null,
    val desccomp: kotlin.String? = null,
    val idprodpai: kotlin.Int? = null,
    val idfornecedor: kotlin.Int? = null,
    val obs: kotlin.String? = null,
    val tipoIva: Int? = null,
    val valorIva: kotlin.Double? = null,
    val tipoIvacompra: Int? = null,
    val valorIvacompra: kotlin.Double? = null,
    val vencomenda: kotlin.String? = null,
    val vreferencia: kotlin.String? = null,
    val quant: kotlin.Int? = null,
    val desconto: kotlin.Double? = null,
    val desconto2: kotlin.Double? = null,
    val upc: kotlin.Double? = null,
    val pcm: kotlin.Double? = null,
    val udc: kotlin.Double? = null,
    val dataentrega: kotlin.String? = null,
    val tara: kotlin.Boolean? = null,
    val taraperdida: kotlin.Boolean? = null,
    val marca: kotlin.Int? = null,
    val reqserial: kotlin.Boolean? = null,
    val tipoprod: Int? = null,
    val objMotivoIsencao: ReasonsExemption? = null,
    val objLote: Lot? = null,
    val usaLote: kotlin.Boolean? = null,
    val seriallist: kotlin.Array<SerialNumber>? = null,
    val salesNumber: kotlin.String? = null,
    val licenseNumber: kotlin.String? = null,
    val contaSNC: kotlin.String? = null,
    val defaultArm: kotlin.String? = null,
    val err: GestError? = null
) {
}