/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param sorting 
 * @param sortingOrder 
 * @param idproduto 
 * @param idProdRegiao 
 * @param visivelAPKAssistencia 
 * @param codigoproduto 
 * @param codigoprodutoFixo 
 * @param codigobarrasproduto 
 * @param codigoforn 
 * @param codigoorcodigobarrasorcodigoforn 
 * @param codigooucodigoBarrasprodutoFixo 
 * @param nomeproduto 
 * @param abreviaturaproduto 
 * @param idfamilia 
 * @param idsubfamilia 
 * @param idmarca 
 * @param idatributo 
 * @param visivelSite 
 * @param visivelPos 
 * @param visivelMopi 
 * @param apenasServicos 
 * @param mostraStock 
 * @param apenasProdutos 
 * @param mostrarEspeciais 
 * @param limitarPesquisaNome 
 * @param idCliente 
 * @param idCategoria 
 * @param precoMax 
 * @param precoMin 
 * @param idFornecedor 
 * @param emDestaque 
 * @param lowestValue 
 * @param bigestValue 
 * @param clienteNome 
 * @param ocultarObsoletos 
 * @param lastUsedForn 
 * @param validade 
 * @param familia 
 * @param marca 
 * @param ignorarNaoMovimentaStock 
 * @param ignorarjaEmContagem 
 * @param getstockaData 
 * @param getstockaDataloja 
 * @param entidadetipo 
 * @param apenasComComponentes 
 * @param numeroRegistosPesquisa 
 * @param numeroPaginaPesquisa 
 * @param objConfigEmpresa 
 * @param produtoSimilaresDe 
 */
data class ProductsSearch (

    val sorting: Int? = null,
    val sortingOrder: Int? = null,
    val idproduto: kotlin.Int? = null,
    val idProdRegiao: kotlin.Int? = null,
    val visivelAPKAssistencia: kotlin.Int? = null,
    val codigoproduto: kotlin.String? = null,
    val codigoprodutoFixo: kotlin.String? = null,
    val codigobarrasproduto: kotlin.String? = null,
    val codigoforn: kotlin.String? = null,
    val codigoorcodigobarrasorcodigoforn: kotlin.String? = null,
    val codigooucodigoBarrasprodutoFixo: kotlin.String? = null,
    val nomeproduto: kotlin.String? = null,
    val abreviaturaproduto: kotlin.String? = null,
    val idfamilia: kotlin.Int? = null,
    val idsubfamilia: kotlin.Int? = null,
    val idmarca: kotlin.Int? = null,
    val idatributo: kotlin.Int? = null,
    val visivelSite: kotlin.Boolean? = null,
    val visivelPos: kotlin.Boolean? = null,
    val visivelMopi: kotlin.Boolean? = null,
    val apenasServicos: kotlin.Boolean? = null,
    val mostraStock: kotlin.Boolean? = null,
    val apenasProdutos: kotlin.Boolean? = null,
    val mostrarEspeciais: kotlin.Boolean? = null,
    val limitarPesquisaNome: kotlin.Boolean? = null,
    val idCliente: kotlin.String? = null,
    val idCategoria: kotlin.Int? = null,
    val precoMax: kotlin.Double? = null,
    val precoMin: kotlin.Double? = null,
    val idFornecedor: kotlin.Int? = null,
    val emDestaque: kotlin.Boolean? = null,
    val lowestValue: kotlin.Boolean? = null,
    val bigestValue: kotlin.Boolean? = null,
    val clienteNome: kotlin.String? = null,
    val ocultarObsoletos: kotlin.Boolean? = null,
    val lastUsedForn: kotlin.Int? = null,
    val validade: java.time.LocalDateTime? = null,
    val familia: kotlin.String? = null,
    val marca: kotlin.String? = null,
    val ignorarNaoMovimentaStock: kotlin.Boolean? = null,
    val ignorarjaEmContagem: kotlin.Boolean? = null,
    val getstockaData: java.time.LocalDateTime? = null,
    val getstockaDataloja: kotlin.String? = null,
    val entidadetipo: kotlin.String? = null,
    val apenasComComponentes: kotlin.Boolean? = null,
    val numeroRegistosPesquisa: kotlin.Int? = null,
    val numeroPaginaPesquisa: kotlin.Int? = null,
    val objConfigEmpresa: ConfigCompany? = null,
    val produtoSimilaresDe: kotlin.Int? = null
) {
}