/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param listaresultados 
 * @param totalresultados 
 * @param err 
 */
data class ProductSearchResult (

    val listaresultados: kotlin.Array<ProductSearch>? = null,
    val totalresultados: kotlin.Int? = null,
    val err: GestError? = null
) {
}