/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param iD 
 * @param descricaoMostrar 
 * @param value 
 * @param displayText 
 */
data class ReasonsExemption (

    val iD: kotlin.Int? = null,
    val descricaoMostrar: kotlin.String? = null,
    val value: kotlin.Int? = null,
    val displayText: kotlin.String? = null
) {
}