/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param internalid 
 * @param serie 
 * @param nome 
 * @param tipoSerie 
 * @param idArmDefault 
 * @param usaDataUltimoDoc 
 * @param imprimirdireto 
 * @param certVersion 
 * @param atcuid 
 * @param numeradorMax 
 * @param dataInicial 
 * @param dataFinal 
 * @param nomeAndDefault 
 * @param isDefault 
 * @param tipoDocNome 
 * @param objTipo 
 */
data class Series (

    val internalid: kotlin.Int? = null,
    val serie: kotlin.String? = null,
    val nome: kotlin.String? = null,
    val tipoSerie: kotlin.Int? = null,
    val idArmDefault: kotlin.String? = null,
    val usaDataUltimoDoc: kotlin.Int? = null,
    val imprimirdireto: kotlin.Int? = null,
    val certVersion: kotlin.Int? = null,
    val atcuid: kotlin.String? = null,
    val numeradorMax: kotlin.Int? = null,
    val dataInicial: java.time.LocalDateTime? = null,
    val dataFinal: java.time.LocalDateTime? = null,
    val nomeAndDefault: kotlin.String? = null,
    val isDefault: kotlin.Boolean? = null,
    val tipoDocNome: kotlin.String? = null,
    val objTipo: TypeDocument? = null
) {
}