/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param ticketN 
 * @param equipamento 
 * @param assunto 
 * @param estado 
 * @param clienteNome 
 * @param clienteMorada 
 * @param clienteCodPostal 
 * @param clienteTelefone 
 * @param clienteTecnico 
 * @param clienteEmail 
 * @param clienteContribuinte 
 */
data class TicketSearch (

    val ticketN: kotlin.String? = null,
    val equipamento: kotlin.String? = null,
    val assunto: kotlin.String? = null,
    val estado: kotlin.String? = null,
    val clienteNome: kotlin.String? = null,
    val clienteMorada: kotlin.String? = null,
    val clienteCodPostal: kotlin.String? = null,
    val clienteTelefone: kotlin.String? = null,
    val clienteTecnico: kotlin.String? = null,
    val clienteEmail: kotlin.String? = null,
    val clienteContribuinte: kotlin.String? = null
) {
}