/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 *
 * @param atualizaPrecoeDataUtlimoDoc
 * @param bloquearDocaVD
 * @param idTipo
 * @param imprimeLogotipo
 * @param tipodoc
 * @param docconversao
 * @param limiteValor
 * @param bancodefault
 * @param obrigaSeleccaoDeBanco
 * @param nome
 * @param diario
 * @param pago
 * @param stock
 * @param movimento
 * @param copias
 * @param subject
 * @param body
 * @param subjecten
 * @param bodyen
 * @param subjectes
 * @param bodyes
 * @param dadospagamento
 * @param escondecabecalho
 * @param mostravalores
 * @param texto
 * @param textoSms
 * @param sendcopy
 * @param sendmail
 * @param ignorarGerarRecibo
 * @param sendsms
 * @param typedoc
 * @param cargadescarga
 * @param serieDefault
 * @param imprimeNCLiente
 * @param imprimirMetodo
 * @param tipoEntidade
 * @param sigla
 * @param siglaSAFT
 * @param mostradoc
 * @param siglaENome
 */
data class TypeDocument (

    val atualizaPrecoeDataUtlimoDoc: kotlin.Boolean? = null,
    val bloquearDocaVD: kotlin.Boolean? = null,
    val idTipo: kotlin.Int? = null,
    val imprimeLogotipo: kotlin.Int? = null,
    val tipodoc: kotlin.Int? = null,
    val docconversao: kotlin.Int? = null,
    val limiteValor: kotlin.Double? = null,
    val bancodefault: kotlin.Int? = null,
    val obrigaSeleccaoDeBanco: kotlin.Boolean? = null,
    val nome: kotlin.String? = null,
    val diario: kotlin.String? = null,
    val pago: kotlin.Boolean? = null,
    val stock: kotlin.String? = null,
    val movimento: kotlin.String? = null,
    val copias: kotlin.Int? = null,
    val subject: kotlin.String? = null,
    val body: kotlin.String? = null,
    val subjecten: kotlin.String? = null,
    val bodyen: kotlin.String? = null,
    val subjectes: kotlin.String? = null,
    val bodyes: kotlin.String? = null,
    val dadospagamento: kotlin.Boolean? = null,
    val escondecabecalho: kotlin.Boolean? = null,
    val mostravalores: kotlin.Boolean? = null,
    val texto: kotlin.String? = null,
    val textoSms: kotlin.String? = null,
    val sendcopy: kotlin.Boolean? = null,
    val sendmail: kotlin.Boolean? = null,
    val ignorarGerarRecibo: kotlin.Boolean? = null,
    val sendsms: kotlin.Boolean? = null,
    val typedoc: kotlin.String? = null,
    val cargadescarga: kotlin.Boolean? = null,
    val serieDefault: kotlin.String? = null,
    val imprimeNCLiente: kotlin.Boolean? = null,
    val imprimirMetodo: Int? = null,
    val tipoEntidade: kotlin.String? = null,
    val sigla: kotlin.String? = null,
    val siglaSAFT: kotlin.String? = null,
    val mostradoc: kotlin.Boolean? = null,
    val siglaENome: kotlin.Any? = null
) {
}