/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

import com.microplus.wsGestplus.models.TypePayment

/**
 * 
 * @param objTipoPagamento 
 * @param documentoPagamento 
 * @param talao 
 * @param referenciaPagamento 
 */
data class TypePaymentDocument (

    val objTipoPagamento: TypePayment? = null,
    val documentoPagamento: kotlin.String? = null,
    val talao: kotlin.String? = null,
    val referenciaPagamento: kotlin.String? = null
) {
}