/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param idTipoPagamento 
 * @param descricao 
 * @param visivelGestplus 
 * @param visivelPosWin 
 * @param visivelRestWin 
 * @param visivelPosMobile 
 * @param visivelGestMobile 
 * @param visivelWebsite 
 * @param pago 
 * @param siglaSaft 
 * @param metodo 
 * @param activo 
 * @param idFornecedor 
 */
data class TypePayment (

    val idTipoPagamento: kotlin.Int? = null,
    val descricao: kotlin.String? = null,
    val visivelGestplus: kotlin.Boolean? = null,
    val visivelPosWin: kotlin.Boolean? = null,
    val visivelRestWin: kotlin.Boolean? = null,
    val visivelPosMobile: kotlin.Boolean? = null,
    val visivelGestMobile: kotlin.Boolean? = null,
    val visivelWebsite: kotlin.Boolean? = null,
    val pago: kotlin.Boolean? = null,
    val siglaSaft: kotlin.String? = null,
    val metodo: kotlin.Int? = null,
    val activo: kotlin.Boolean? = null,
    val idFornecedor: kotlin.Int? = null
) {
}