/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param idUtilizador 
 * @param nome 
 * @param login 
 * @param password 
 * @param pin 
 * @param idLoja 
 * @param email 
 * @param idTipoPrinter 
 * @param ipPrinter 
 * @param bloqueado 
 * @param inativo 
 * @param enableSuporte 
 * @param defDocVendas 
 * @param defDocCompras 
 * @param defDocStocks 
 * @param hasToChangePass 
 * @param serieDefault 
 * @param filtrarPesqApenasUser 
 * @param phonenumber 
 * @param countryCode 
 * @param idProfile 
 * @param idViatura 
 */
data class User (

    val idUtilizador: kotlin.Int? = null,
    val nome: kotlin.String? = null,
    val login: kotlin.String? = null,
    val password: kotlin.String? = null,
    val pin: kotlin.String? = null,
    val idLoja: kotlin.String? = null,
    val email: kotlin.String? = null,
    val idTipoPrinter: Int? = null,
    val ipPrinter: kotlin.String? = null,
    val bloqueado: kotlin.Boolean? = null,
    val inativo: kotlin.Boolean? = null,
    val enableSuporte: kotlin.Boolean? = null,
    val defDocVendas: kotlin.Int? = null,
    val defDocCompras: kotlin.Int? = null,
    val defDocStocks: kotlin.Int? = null,
    val hasToChangePass: kotlin.Int? = null,
    val serieDefault: kotlin.String? = null,
    val filtrarPesqApenasUser: kotlin.Int? = null,
    val phonenumber: kotlin.String? = null,
    val countryCode: kotlin.String? = null,
    val idProfile: kotlin.Int? = null,
    val idViatura: kotlin.Int? = null
) {
}