/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models


/**
 * 
 * @param viaturaID 
 * @param matricula 
 * @param tipoId 
 * @param numeroMotor 
 * @param numeroChassi 
 * @param anoFabricacao 
 * @param cor 
 * @param capacidade 
 * @param estado 
 * @param idProduto 
 * @param posLastUpdate 
 * @param posLat 
 * @param posLng 
 */
data class Viatura (

    val viaturaID: kotlin.Int? = null,
    val matricula: kotlin.String? = null,
    val tipoId: kotlin.Int? = null,
    val numeroMotor: kotlin.String? = null,
    val numeroChassi: kotlin.String? = null,
    val anoFabricacao: kotlin.Int? = null,
    val cor: kotlin.String? = null,
    val capacidade: kotlin.Int? = null,
    val estado: kotlin.String? = null,
    val idProduto: kotlin.Int? = null,
    val posLastUpdate: java.time.LocalDateTime? = null,
    val posLat: kotlin.Double? = null,
    val posLng: kotlin.Double? = null
) {
}